### PR TITLE
PODAAC-2545: Change "Time" fields to date-time type

### PR DESCRIPTION
**Pull request by skorper**
Addresses #11 

[Jira ticket](https://jira.jpl.nasa.gov/browse/PODAAC-2545)

Using Python jsonschema, I can show that a timestamp like `2017-09-30T03:42:29.791198` fails validation whereas a timestamp like `2017-09-30T03:42:29Z` passes validation.

```py
>>> data_file = open('samples/cumulus_sns_v1.4_notification.json')
>>> schema_file = open('cumulus_sns_schema.json')
>>> data = json.loads(data_file.read())
>>> schema = json.loads(schema_file.read())
>>> jsonschema.validate(data, schema, format_checker=jsonschema.FormatChecker())
>>> data['submissionTime'] = '2017-09-30T03:42:29.791198'
>>> jsonschema.validate(data, schema, format_checker=jsonschema.FormatChecker())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: '2017-09-30T03:42:29.791198' is not a 'date-time'

Failed validating 'format' in schema['properties']['submissionTime']:
    {'description': 'The time the message was created (and presumably '
                    'sent) to the publication mechanism.',
     'format': 'date-time',
     'type': 'string'}

On instance['submissionTime']:
    '2017-09-30T03:42:29.791198'
```

Code that should be updated to match new schema:

* C2C
  - cnm.py `submissionTime` uses `datetime.datetime.utcnow().isoformat()` to generate a timestamp, which results in a timestamp like `2020-10-13T00:30:42.168995`. That timestamp does not match the RFC 3339 date-time format, and would need to be updated.
    - Additionally, `jsonschema.validate()` does not validate format by default, so the CNM validation code should be modified to validate timestamp format.
  - All C2C tools use cnm.py (include cnm_s6.py), so this change would only be necessary in one place.
  - migration-data-purger would not be affected, as the timestamp fields are not used in the lambda
* SWOT CNM
  - This lambda does not appear to interact with (read or write) any timestamp values from the CNM message
* cnm-to-granule
  - `recievedTime` appears to use the format `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`. For example, `"receivedTime": "2020-10-13T15:53:55.538Z"`, which does not match the RFC 3339 timestamp.
* cnm-response
  - `processCompleteTime` has the same issue as cnm-to-granule. For example: `"processCompleteTime":"2020-10-13T16:04:52.256"`

I went with version 1.4.2, thoughts?

### CODE REVIEW

**Comment by skorper** [comment]
Milliseconds are also valid: 

```py
>>> data['submissionTime'] = '2017-09-30T03:42:29.791198Z'
>>> jsonschema.validate(data, schema, format_checker=jsonschema.FormatChecker())
>>> 

```

**Comment by ngachung** [comment]
@skorper Can you please also update the time value in all the other samples/*.json and update test.sh to validate using jsonschema.FormatChecker() Thanks!

**Review by ngachung — CHANGES_REQUESTED** [review]
Please see comment

**Comment by skorper** [comment]
@ngachung I've updated the samples, but I'm still researching how to do format checking using the jsonschema CLI.

**Review by ngachung — APPROVED** [review]

**Pull request merged**
